version: '3'
services:
  db_mysql:
    container_name: db_mysql
    build:
      context: ./MoneyManager.DB
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3306:3306
  webapi:
    container_name: webapi
    build:
      context: ./MoneyManager.API
      dockerfile: Dockerfile
    restart: always
    ports:
      - 50000:80
    depends_on:
      - db_mysql
#  razorpages:
#    container_name: razorpages
#    build:
#      context: ./MoneyManager.Pages
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - 50001:80
#    depends_on:
#      - db_mysql
#      - webapi