version: '3.3'
services:
  database:
    build: ./Database
    container_name: database
    restart: always
    ports:
      - 14333:1433
  moneymanager:
    build: ./RazorPages.proj
    container_name: moneymanager
    restart: always
    ports:
      - 58080:80
    depends_on:
      - database